### ISSUE TITLE
My slam.launch Can't display the map

### ISSUE THREAD

**Issue by HitSZwang** [chvmp/champ#10]
![123](https://user-images.githubusercontent.com/63332427/90995436-8f74e000-e5ee-11ea-8d39-60d7f5eda42b.png)

In my model_config, I can control the movement of the robots in gazebo and rviz by controlling champ_teleop, but the slam.launch of the mode_config exported by my self-check through the assistant cannot display the map, which is very dark. I can’t press 2D Nav Goal to control the movement of the robot, as shown in the picture. Thanks.

**Comment by HitSZwang** [comment]
![123](https://user-images.githubusercontent.com/63332427/90995504-b6cbad00-e5ee-11ea-8822-01e09a2d68b4.png)

**Comment by grassjelly** [comment]
You need to add sensors (LIDAR and IMU) in your robot's model for this demo to work. You can include this xacro file as a reference: https://github.com/chvmp/champ/blob/master/champ_description/urdf/champ.urdf.xacro#L43

**Comment by grassjelly** [comment]
Hey @HitSZwang the current config for MIT cheetah hasn't been configured to work in Gazebo yet. Are you okay to include it in the supported robots? Thanks!

**Comment by HitSZwang** [comment]
ok @grassjelly but i dont know how to include it. and my robot is imitative robot which is same to mini cheetah

**Comment by grassjelly** [comment]
@HitSZwang You just have to push it to your github repository and I'll link to your page.

**Comment by HitSZwang** [comment]
https://github.com/HitSZwang/mini-cheetah-gazebo-urdf

**Comment by grassjelly** [comment]
thanks! Will send a PR once I’ve tested everything

**Comment by grassjelly** [comment]
@HitSZwang Do you have a downsized version of the STL files? I managed to make it work in Gazebo but the Real Time Factor keeps dropping, probably due to the huge file size of the meshes. Would appreciate if you can upload that to so I can do further tests before sending the PR. Thanks!

**Comment by grassjelly** [comment]
A working Gazebo model for the Mini Cheetah is now available. Please check  https://github.com/chvmp/robots  
![mini_cheetah](https://user-images.githubusercontent.com/5070395/92573248-13e68480-f2b8-11ea-81b6-115aa1423da0.gif)
