### ISSUE TITLE
Robot legs move in opposite directions than what's showing on rviz using joints gui

### ISSUE THREAD

**Issue by TonyLiu836** [chvmp/champ#101]
Hi,

I've been stuck on trying to figure out why the legs on the left side of my robot move in opposite directions than what's showing on rviz when using the joint gui. I followed the hardwar_integration guide and mounted the servos at their zero positions with the robot's legs pointing straight down. Additionally, the shoulder/hip actuator can only move in one direction, as it is already at the limit of it motion range according to the directions in the hardware_integration guide. Is this intended? 

Thanks!

**Comment by RamCharanThota** [comment]
On of the Simple check we did is, whether all the axis defined in the leg joints follow the required champ configuration which is as shown in figure
![joint_axis_config](https://user-images.githubusercontent.com/67779589/189011990-65d6fead-6b9f-4609-a7f2-23acd44d7895.png).
Hope it will help to resolve the issue

**Comment by yoggi56** [comment]
I encountered the same issue when I had wrong rotation directions in joints in URDF file of my robot. Check champ.urdf file. You should have these values for your robot:
1. hip_joint: <axis xyz="1 0 0"/>
2. upper_leg_joint: <axis xyz="0 1 0"/>
3. lower_leg_joint: <axis xyz="0 1 0"/>
