### ISSUE TITLE
implement multi-minicheetah

### ISSUE THREAD

**Issue by YandongJi** [chvmp/champ#13]
Hi, I implemented multiple minicheetah the same way as I did for champ. I added some namespaces and tf_prefix. However, the implementation works for champ but not for cheetah. Could you check it? Thx

**Comment by grassjelly** [comment]
are you using the most recent version of the Mini Cheetah's description package? Fixed some issues related to this problem last night. https://github.com/chvmp/mini-cheetah-gazebo-urdf/commit/8e39596b6041fb3827717978e8a26584db4a14da

**Comment by YandongJi** [comment]
that's the problem. Fixed, thx!
