### ISSUE TITLE
controlling of mini cheetah

### ISSUE THREAD

**Issue by YandongJi** [chvmp/champ#14]
Hi, it seems that the controlling of mini-cheetah needs some improvement. When I use **teleop** and type "i" to make it go straight, it's struggling and not going in expectation. But if type "<" to make it go backwards, it performs better. Wondering whether it's the problem of pid parameter or other bugs. Thx!

**Comment by grassjelly** [comment]
Hi,

You can fine-tune the PID constants here: https://github.com/chvmp/robots/blob/master/configs/mini_cheetah_config/config/ros_control/ros_control.yaml#L23-L34

**Comment by YandongJi** [comment]
yeah, it may be the problem of foot friction. the feet keep slipping while going forward. are there any methods I can adjust that? I checked friction in "default.world" but there I can only adjust the plane friction instead of foot friction.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by grassjelly** [comment]
Sure, you can tweak it from here: https://github.com/chvmp/mini-cheetah-gazebo-urdf/blob/master/yobo_model/yobotics_description/xacro/gazebo.xacro#L183-L190 (this is only for front-left foot)

**Comment by YandongJi** [comment]
my robots are still slipping. Is your robot in gazebo running well? (use teleop to control) Many thx!

**Comment by grassjelly** [comment]
Yes! But I only tested it with one robot instance. May I know what's your current Real Time Factor in Gazebo while running multiple robots? How many robots are you running?

**Comment by YandongJi** [comment]
I'm running 4 robots and the Real Time Factor is 0.13. Seems a bit low. I changed the desired RTF in .world files but can't solve the problem. Also could you try whether you can make it going straight by only typing "i"?

**Comment by grassjelly** [comment]
Yes, I can control the robot straight when pressing 'i' in teleop. I suspect your RTF is too low to get the physics right. Have you tried spawning just one robot?

**Comment by YandongJi** [comment]
yeah, I just tried on champ. The RTF is 0.2-0.4.

**Comment by YandongJi** [comment]
Can I know your RTF?

**Comment by grassjelly** [comment]
RTF's ~ 1.0 .Here's how the robot behaves on walking test

![cheetah2](https://user-images.githubusercontent.com/5070395/94150233-72f8eb80-feab-11ea-8d08-9959470e3b21.gif)

**Comment by YandongJi** [comment]
Thx, a higher performance computer solved the problem.

**Comment by peci1** [comment]
@grassjelly I think telling that low RTF should be the major problem crippling champ is not right. It's actually quite the opposite on most machines with 4+ cores. Gazebo can scarcely utilize all cores and gets slowed down in e.g. rendering or some other single-threaded tasks, so there are still some cores with free computational power that can be e.g. used by CHAMP. And the slower is the simulation, the more time has each control loop to finish! So actually lower RTF should mean the same or better performance of CHAMP. I did an experiment on my machine which usually achieves about 0.6 RTF. I set it manually to 0.1 and CHAMP got crippled again. It seems to me there has to be a component of CHAMP that wrongly uses simulation time. I'll try to investigate as this is a blocker for me.

**Comment by peci1** [comment]
To prove my point: here are plots of one joint from `/joint_group_position_controller/command` that differ only in RTF. CHAMP was given exactly the same cmd_vel in both cases. The x and y axes in both plots have the same scale and the rqt_plot was run with `use_sim_time` set to true.

RTF 0.1

![Snímek z 2021-03-23 23-31-37](https://user-images.githubusercontent.com/182533/112227787-7b4e9b00-8c30-11eb-9f5a-416dc1abfedd.png)

RTF 1.0 (or what my computer can do, about 0.6-0.8)

![Snímek z 2021-03-23 23-33-18](https://user-images.githubusercontent.com/182533/112227828-8b667a80-8c30-11eb-9f2b-abf5d4e841d7.png)

**Comment by peci1** [comment]
But the rate at which the commands are published is the same (200 Hz).

**Comment by peci1** [comment]
Got it: https://github.com/chvmp/libchamp/blob/cc884617153c52c0fe7e288d191acd2ac95f1d8b/leg_controller/phase_generator.h#L80 . I'll try to send a PR allowing proper use of simulation time.

**Comment by peci1** [comment]
The PR fixing running using simulation time is here: https://github.com/chvmp/champ/pull/48 .
