### ISSUE TITLE
Error When running base drive in RVIZ

### ISSUE THREAD

**Issue by abdksyed** [chvmp/champ#18]
Hi,
When I am running the command
```roslaunch champ_config bringup.launch rviz:=true```
I am getting this error, and the RVIZ GUI is opening up, but I am unable to perform any task like moving forward or turning etc using keyboard controls of (u,i,o,j......).
![image](https://user-images.githubusercontent.com/62547949/96075569-f2854380-0ec8-11eb-9bd2-193936d26473.png)

**Comment by grassjelly** [comment]
Can you help me check the following:

1. Have you build the workspace:

`cd ~/<your_ws>/ && catkin_make
`

2. You have sourced the workspace before running the demos:

`source ~/<your_ws>/devel/setup.bash
`

3. You have yocs_velocity_smoother in your '_src_' folder

```
cd ~/<your_ws>/src
git clone https://github.com/chvmp/yocs_velocity_smoother
cd ..
catkin_make
```

**Comment by abdksyed** [comment]
I tried reinstalling everything from scratch, and it's working fine now.
Thanks for the help anyways.

**Comment by trunc8** [comment]
I am facing a similar issue without any explicit error messages on the terminal.
![image](https://user-images.githubusercontent.com/50488330/97114179-f1e47c80-1714-11eb-9062-fc77bd966b86.png)
I am unable to move the bot using teleop.launch.
I double-checked and followed the steps mentioned [earlier](https://github.com/chvmp/champ/issues/18#issuecomment-709172112) by grassjelly. Even re-installing wasn't of help.
After firing up teleop.launch, performing `rostopic echo /cmd_vel` displays nothing. Likewise for `rostopic echo \body_pose`.
Any suggestions would be greatly appreciated!

**Comment by abdksyed** [comment]
After launching both terminals (teleop and rviz), press and HOLD the key in the controls terminal (U or I or O), the bot will move

**Comment by trunc8** [comment]
It did! Thanks a lot!

**Comment by Aniruddha7** [comment]
It seems like the warning in the screenshot are not error messages but
related to velocities that meant sensors are not getting proper input to
move

**Comment by trunc8** [comment]
Haha right! I spent a long time going through the code imagining that those warnings caused the bot to not move. Can we display a more explicit message in the teleop.launch to keep the key pressed?
![image](https://user-images.githubusercontent.com/50488330/97115845-3b39c980-171f-11eb-832c-c2747032ae73.png)
The last line gave me the impression that it's constantly publishing to the velocity topics.

**Comment by Aniruddha7** [comment]
lol! Yes, you just need to follow those instructions. In the code there is
a docstring for this message and you can make changes locally by adding the
statement. But you can check with the author of the GitHub if you want to
publish it .

**Comment by offjangir** [comment]
I am having a little problem @grassjelly   whenever I run any config ANYmal or Champ itself  rviz does not show any colors or the robot doesn't appear correctly I attached a screen shot Please help!

![Screenshot from 2021-03-07 18-16-04](https://user-images.githubusercontent.com/60678034/110240427-dfefd180-7f71-11eb-8846-36a1692ef3f1.jpeg)

**Comment by offjangir** [comment]
@trunc8  do you have any suggestions?

**Comment by grassjelly** [comment]
hey @offjangir are there any errors when you run the launch files?

**Comment by offjangir** [comment]
@grassjelly  no , not any  error just 2 warnings  also this is happening for all the configurations

**Comment by offjangir** [comment]
[ WARN] [1615125291.797946407]: Warning: Some linear velocity entries in parameter imu0_config are listed true, but an sensor_msgs/Imu contains no information about linear velocities
[ WARN] [1615125291.802205050]: Warning: imu/data is listed as an input topic, but all its update variables are false

**Comment by grassjelly** [comment]
@can you post your rqt_graph here?

**Comment by offjangir** [comment]
here it is
![Screenshot from 2021-03-07 19-35-26](https://user-images.githubusercontent.com/60678034/110242643-f8191e00-7f7c-11eb-8fd9-c1cf3eef8cee.png)

**Comment by offjangir** [comment]
@grassjelly  can you something that i am doing wrong here
