### ISSUE TITLE
2D Nav Goal - robot moving in stationery position during SLAM

### ISSUE THREAD

**Issue by bluetulip89** [chvmp/champ#2]
![default_gzclient_camera(1)-2020-05-12T14_57_29 481620](https://user-images.githubusercontent.com/3772941/81667894-8312b000-9461-11ea-9a0b-b1656125bec8.jpg)

While executing 2d nav goal  and giving goal to robot for SLAM, the 4 legs of the robot are moving but yet the robot is same position. 

Kindly look into it and help

**Comment by bluetulip89** [comment]
The issued has been resolved by re-installing gazebo_ros_pkgs. I am using kinetic , so I did cloned the following and did catkin_make again. After this SLAM worked fine . 

Here is the link I used
git clone https://github.com/ros-simulation/gazebo_ros_pkgs.git -b kinetic-devel

**Comment by grassjelly** [comment]
thanks for spotting this. fixed https://github.com/chvmp/champ/commit/35e6457ac0e3831560e9870fce43eaa0f40b5926
