### ISSUE TITLE
Working on open Quadrupeder (teensy 4.0) How-to?! 

### ISSUE THREAD

**Issue by elpimous** [chvmp/champ#21]
Hi.
Champ simulations 👍

Now real-time. 
Working on Jetson, connected to Adham/Maurice/Mano board (open quadrupeder/spotmicroAI) , containing a teensy 4.0.

Teensy is rosserial ready (Maurice Rahme firmware /moribot) 

Do I just need to run the next lines, to be able to use your package on my Dog?

```
<!-- Sensor Interface Node -->
<node pkg="rosserial_python" type="serial_node.py" name="serial_node">
    <param name="port" value="/dev/ttyS0"/> <!-- HW Serial -->
    <param name="baud" value="500000"/>  <!-- must match Teensy -->
  </node>
```
Thanks a lot. 

Vincent.

**Comment by grassjelly** [comment]
HI Vincent,

I’m not sure on Open Quadruped’s firmware but these guidelines might help you setup your real robot: https://github.com/chvmp/champ/wiki/Hardware-Integration.

What I would recommend is to write direct comms interface between your Teensy and Linux Machine.

**Comment by Quothd** [comment]
On the Jetson, you need to specify the serial port as: 

<param name="port" value="/dev/ttyTHS1"/>
