### ISSUE TITLE
Running this on ROS-noetic

### ISSUE THREAD

**Issue by m2kulkarni** [chvmp/champ#3]
I am trying to run this on latest ros version but it doesnt seem to work. When i follow the installation steps, catkin_make runs successfully but with error for yocs_velocity smoother. 
![Screenshot from 2020-06-07 22-25-19](https://user-images.githubusercontent.com/56233197/83975481-e2a19580-a911-11ea-905d-30c5d0fab01c.png)
I also tried cloning yocs_velocity_smoother from upstream, but still it persists

**Comment by bluetulip89** [comment]
This champ package is intended for kinetic or melodic. For the latest release we need to make some modifications to work. 

The "ecl_threads" ROS package is missing. Kindly install the package from this link (http://wiki.ros.org/ecl_threads) and let me know if you have any other errors.

**Comment by m2kulkarni** [comment]
Hey, I did that, i built from source ecl packages and when i did catkin_make, i had no errors in that. It built successfully(no ecl errors like last time). But when i try to run `roslaunch champ_config bringup.launch rviz:=true` i get rviz with only a white mesh and lots of error in terminal
![Screenshot from 2020-06-08 11-00-46](https://user-images.githubusercontent.com/56233197/83995696-ba4c8200-a977-11ea-875c-7c6945d247fc.png)

Also when i run `roslaunch champ_config gazebo.launch` gazebo gets stuck on preparing your world without any errors.

Maybe champ requires other packages which arent included? If so can you list them. Thanks. 
1. Hector_sensors_description

**Comment by grassjelly** [comment]
hi, can you try this branch? I suspect it's publishing the transforms before the controller has started. Temporarily added some flag to ensure the controller has started before publishing data.

**Comment by m2kulkarni** [comment]
Which Branch? Master or the noetic-bug branch?

**Comment by grassjelly** [comment]
sorry missed the link. Updated my comment.

**Comment by m2kulkarni** [comment]
Still no change, same thing happens :/

**Comment by grassjelly** [comment]
did you rebuild the workspace and source it again?

**Comment by m2kulkarni** [comment]
Yes, did that.

**Comment by grassjelly** [comment]
Sorry can’t replicate this issue in Melodic. I suspect it could be related to the pose estimation that was recently added. Meanwhile you can give the previous commit a try. https://github.com/chvmp/champ/tree/5e0861d60e2e1b8597db93b3adbc5562f4bd31fd

**Comment by m2kulkarni** [comment]
I tried that too. Here are the output files for 
1. git show-branch
2. catkin_make
3. roslaunch champ_config bringup.launch rviz:=true 
I did not find anything peculiar.
[out.txt](https://github.com/chvmp/champ/files/4753635/out.txt)

**Comment by grassjelly** [comment]
hey @m2kulkarni . Saw your SLAM benchmarks. Did you manage to run this on Noetic?

**Comment by lenia209911** [comment]
Hello
Can you please help?
Why doesn't gazebo.launch (mini_cheetah_config) get started, but just lies down on the ground? It feels like it won't launch TF
* Ubuntu 18.04 ros-melodic gazebo 9.13.1
![Снимок экрана от 2020-07-22 13-04-01](https://user-images.githubusercontent.com/55525182/88163875-f97b1d80-cc1b-11ea-84bf-a7e0f74fdf4d.png)

**Comment by grassjelly** [comment]
@lenia209911 hi, can you please post this as a separate issue.

**Comment by nickle-fang** [comment]
@grassjelly I meet the same problem with @m2kulkarni . My OS is Ubuntu 20.04.

**Comment by flynneva** [comment]
hey so i just built this package on the master branch on Ubuntu 20.04 using noetic. it builds fine as long as you have the dependencies installed.

the problem i think you are running into is one that `rosdep install` isnt actually installing your dependencies.  [I ran into the same problem and have created an issue](https://github.com/ros-infrastructure/rosdep/issues/779) over on the `rosdep` repo to track it.

to run `rosdep install` on noetic on ubuntu 20.04 run it while specifying your OS's version:
```
rosdep install --os=ubuntu:focal
```

**Comment by flynneva** [comment]
what is a problem though is that it looks like some dependencies are not available yet for noetic:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
yobotics_description: Cannot locate rosdep definition for [hector_sensors_description]
mini_ros: Cannot locate rosdep definition for [hector_sensors_description]
champ_navigation: Cannot locate rosdep definition for [hector_mapping]
opendog_description: Cannot locate rosdep definition for [hector_sensors_description]
dkitty_description: Cannot locate rosdep definition for [hector_sensors_description]
champ_description: Cannot locate rosdep definition for [hector_sensors_description]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
```

**Comment by flynneva** [comment]
created tracking issue for the Noetic dependencies #15
