### ISSUE TITLE
Minimal hardware requirement for running the simulation

### ISSUE THREAD

**Issue by yezhicheng99** [chvmp/champ#31]
Hi, when I run the gazebo simulation, the robot keeps slipping a lot and there exists a large odom error from the state_estimator node. Probably it's the same issue as issue #14, because the real time factor is less than 0.4. Could you tell your computer configuration details? Thank you!

**Comment by grassjelly** [comment]
hi may I know which robot are you running?

**Comment by yezhicheng99** [comment]
Thank you for your reply, both champ and spot have this issue in my laptop, not tried other robot.
