### ISSUE TITLE
Build Issue related to libbullet version

### ISSUE THREAD

**Issue by dlee640** [chvmp/champ#33]
Hello. I am getting a catkin_make error that is very weird.

I have Ubuntu18.04 with Gazebo9. I am hetting No package 'bullet' found errror, that seems unsolvable even by executing `sudo apt-get install libbullet-dev`. Currently, my system says that I have libbullet 2.87 installed so I am very lost on why this is happening.

![Screenshot from 2021-02-26 14-44-49](https://user-images.githubusercontent.com/60672433/109347641-74a35280-7841-11eb-9b8b-852a35aa66de.png)
Has anyone had this issue or know how to solve it? I feel like this is a path issue related to gazebo..

**Comment by grassjelly** [comment]
looks like you have a virtual environment activated. Could it be clashing with that?

**Comment by grassjelly** [comment]
Hey @dlee640 . Did you manage to resolve this?

**Comment by dlee640** [comment]
Yes, sorry for the late response.

**Comment by grassjelly** [comment]
@dlee640 do you mind sharing how you resolve this for future references?

**Comment by dlee640** [comment]
probably not the best solution, I reinstalled ubuntu.
