### ISSUE TITLE
Not able to launch champ in gazebo

### ISSUE THREAD

**Issue by offjangir** [chvmp/champ#37]
am facing an issue when i launch champ config in gazebo  with
using Ros Melodic gazebo updated to 9+
$roslaunch champ_config gazebo.launch
![Screenshot from 2021-03-07 22-20-03](https://user-images.githubusercontent.com/60678034/110247703-91532f00-7f93-11eb-93b0-4fbc42ed8c3c.png)

**Comment by grassjelly** [comment]
It usually takes a while to load when you’re running it for the first time

**Comment by offjangir** [comment]
i waited for like 10 mins for it to start!

**Comment by offjangir** [comment]
yeah there was a lil problem due to my machine . but  it resolved .  but @grassjelly  can you take a look at my other query. that i asked
