### ISSUE TITLE
Bringup is failing to launch the robot model in rviz

### ISSUE THREAD

**Issue by offjangir** [chvmp/champ#38]
![Screenshot from 2021-03-08 14-57-35](https://user-images.githubusercontent.com/60678034/110302028-cd7fa180-801e-11eb-823b-9a54cc59aabc.png)
![Screenshot from 2021-03-07 19-35-26](https://user-images.githubusercontent.com/60678034/110302076-da9c9080-801e-11eb-9321-75ce9d1240dc.png)

**Comment by grassjelly** [comment]
hey @offjangir could you post your TF graph here too? Thanks

**Comment by offjangir** [comment]
@grassjelly  the tf graph is completely empty
![Screenshot from 2021-03-08 16-05-11](https://user-images.githubusercontent.com/60678034/110310048-15ef8d00-8028-11eb-8ebe-19f273157eef.png)

$rosrun tf view_frames
$evince frames.pdf

**Comment by grassjelly** [comment]
strange. Do you have robot_state_publisher, robot_state_publisher, and robot_localization?

**Comment by offjangir** [comment]
yes i have that. idk what the problem is.. gazebo simulations are running perfectly fine

**Comment by grassjelly** [comment]
I can’t replicate this error. What’s your tf graph like when running in Gazebo?

**Comment by offjangir** [comment]
no tf data @grassjelly 
plus again the launch is stuck at the starting screen for gazebo too 

![Screenshot from 2021-03-10 00-02-35](https://user-images.githubusercontent.com/60678034/110520087-0bbab500-8134-11eb-9e42-2d95efcd5378.png)

**Comment by offjangir** [comment]
even if it starts the champ/ANYmal doesnt load

**Comment by offjangir** [comment]
![Uploading Screenshot from 2021-03-10 00-15-39.png…]()

**Comment by offjangir** [comment]
![Screenshot from 2021-03-10 00-15-39](https://user-images.githubusercontent.com/60678034/110521540-df079d00-8135-11eb-8b4d-7464fbb61a54.png)

**Comment by offjangir** [comment]
[frames.pdf](https://github.com/chvmp/champ/files/6112232/frames.pdf)

**Comment by offjangir** [comment]
i did have such problem in turtlebot3 i resolved it by export TURTLEBOT3_MODEL= modelname   
but I dont think it will work here

**Comment by grassjelly** [comment]
Are you able to receive the joint_states ? Are you passing any argument to the launch file when you run bringup.launch?

**Comment by grassjelly** [comment]
Hey @offjangir . Have you resolved this issue?

**Comment by deardost** [comment]
Hi there @offjangir 
Just change the **Fixed Frame** under **Global Options** to `base_link`. It will resolve all the errors. Then change it back to `odom`
I had the same issue as you. I resolved it this way.

**Comment by deardost** [comment]
Can anyone say the reason why it works only when you change it to `base_link` first before fixing it back to `odom` ?

**Comment by grassjelly** [comment]
@deardos Does this happen when you run bringup.launch without passing rviz argument and launching the rviz config file independently? My suspicion is that odom->base_link is not published yet when RVIZ starts to load the asset.

**Comment by deardost** [comment]
@grassjelly No. 
![Screenshot from 2021-03-23 19-02-49](https://user-images.githubusercontent.com/74898176/112154607-7119a600-8c0a-11eb-92c4-baa58d2a181b.png)
I follow the steps above exactly as they are. But even then, it happens that the robot is white and I can't perform the manual walking i-e teleop operations on the bot. When I change fixed frame to base_link, the robot gets everything corrected. Then I change it back to odom to make the robot, using keyboard.

**Comment by deardost** [comment]
I am using ROS Noetic.
