### ISSUE TITLE
Hardware Documentation: Please add, need help?

### ISSUE THREAD

**Issue by arminf82** [chvmp/champ#4]
Regarding 

3. Running your own robot:

TODO:

Hardware Documentation
Microcontroller based configuration

I really want to build my own robot and I am very excited about the Hardware documentation. If you wish I can help writing the git pages.

**Comment by grassjelly** [comment]
Hi @arminf82 nice to see you here. I'm currently developing the hardware and will release the documentation once I get a stable version. 

Thanks for offering your help. Maybe we can take this offline how we can work together on the pages. 

Closing this for now.
