### ISSUE TITLE
Chiken head rviz simulation problem : didn't work

### ISSUE THREAD

**Issue by junghs1040** [chvmp/champ#41]
There is no base_mount information in champ_arm.urdf 
and in mesh file there is no base_mount STL file

so when i launch the demo.launch to simulate the chicken_head in rviz
No transform from [base] to [/odom] error occured and didn't move

**Comment by grassjelly** [comment]
Hi, can you post this on the chicken_head package instead?

**Comment by junghs1040** [comment]
Sure. I posted it!
