### ISSUE TITLE
Don't start gazebo.launch mini_cheetah_config

### ISSUE THREAD

**Issue by lenia209911** [chvmp/champ#5]
Hello
Can you please help?
Why doesn't gazebo.launch (mini_cheetah_config) get started, but just lies down on the ground? It feels like it won't launch TF

Ubuntu 18.04 ros-melodic gazebo 9.13.1
![Снимок экрана от 2020-07-22 13-04-01](https://user-images.githubusercontent.com/55525182/88164205-802ffa80-cc1c-11ea-87fe-08abdf0b1d7b.png)

**Comment by grassjelly** [comment]
Hi,

The Mini Cheetah's URDF in the preconfigured robots is barebones. It doesn't include the inertia and transmissions required to be simulated in Gazebo. You can check out the default robot for reference https://github.com/chvmp/champ/blob/master/champ_description/urdf/champ.urdf

**Comment by lenia209911** [comment]
The champ robot is also in the gazebo)

**Comment by grassjelly** [comment]
You can follow the following commits how to integrate URDFs with Gazebo https://github.com/moribots/spot_mini_mini/pull/7/commits

**Comment by grassjelly** [comment]
A working Gazebo model for the Mini Cheetah is now available. Please check  https://github.com/chvmp/robots  
![mini_cheetah](https://user-images.githubusercontent.com/5070395/92573248-13e68480-f2b8-11ea-81b6-115aa1423da0.gif)
