### ISSUE TITLE
Problem in ROS-Noetic

### ISSUE THREAD

**Issue by alphabeta97** [chvmp/champ#50]
Hello,
I'm running champ in Noetic, while running I'm encountering few errors and also robot model is not completely visible. (I'm running ROS Noetic on WSL2 Windows.)
This is the error file
[error.txt](https://github.com/chvmp/champ/files/6298184/error.txt)

![Screenshot_2021-04-12_21-34-12](https://user-images.githubusercontent.com/64826804/114425805-0ccd7f00-9bd7-11eb-970e-89ef816cef9b.png)

**Comment by Alexbeast-CN** [comment]
Because ROS Noetic using python3 as it dependant but this package is using python. That means you should try ROS Melodic.

**Comment by alphabeta97** [comment]
Thanks,
I'll try it out on Melodic.
