### ISSUE TITLE
Can we plot rqt graph?

### ISSUE THREAD

**Issue by alphabeta97** [chvmp/champ#54]
can we plot graph using rqt for model, like we can get the value of joint state or value from odom, cmd_vel etc.?

**Comment by grassjelly** [comment]
hey @alphabeta97 . Yes you can. Alternatively, you can also use [PlotJuggler](https://github.com/facontidavide/PlotJuggler) and select the topic you'd like to monitor/visualize.

**Comment by alphabeta97** [comment]
I tried PlotJuggler and it is much easier to use compared to rqt.
Thank You.
