### ISSUE TITLE
RTF very slow running on Jetson Nano

### ISSUE THREAD

**Issue by fus3** [chvmp/champ#55]
Hello im running champ on a Jetson Nano the problem comes when running the gazebo simulation, because the maximum RTF achieved is 0.15 or 0.16. I tried updating real_time_update to 0 but the RTF stills the same, also i tried changing the step but then the joints go crazy. When running a turtlebot3 simulation on gazebo the RTF is about ~1. Im using the jetson through vnc viewer so i was wondering if that was the problem, so i tried the jetson through hdmi but it still happening the same, the fps are about 65 so i dont think that the problem comes from the hardware, any ideas?  As you can see i also tried deleting all the props on the scene but nothing happens.

![image](https://user-images.githubusercontent.com/75036029/118409858-c1eacf80-b68c-11eb-925a-8e71a7b4a99d.png)

**Comment by fus3** [comment]
Also i add here a question/problem that im having when creating a node for the hardware that suscribes to /joint_group_position_controller/command/ in gazebo it publishes the positions but is not publishing any position when running bringup.launch on rviz but if input harware_connected:=true to make it publish the positions then the joints go crazy. Following the hardware page on the wiki i cannot know whats happening.

**Comment by grassjelly** [comment]
I haven't tried running the simulation on Jetson Nano, but the low RTF could be due to the computational constraint on your SBC. I recommend running the simulation at least on a laptop. You can check out this thread https://github.com/chvmp/champ/issues/14

Could you post the hardware problem as another thread?
