### ISSUE TITLE
Error with champ robot model

### ISSUE THREAD

**Issue by mgl-sg** [chvmp/champ#57]
Ran the following commands: 
roslaunch champ_config gazebo.launch
roslaunch champ_config navigate.launch rviz:=true

But there was some issue with the robot model as seen in the image below. Additionally, the cost maps in front of the robot shows phantom lines. Not sure why this is the case?
![Champ navigate issue](https://user-images.githubusercontent.com/83993286/121307561-b197de80-c932-11eb-8ae1-206860a15192.png)

**Comment by grassjelly** [comment]
which ROS distro are you using?

**Comment by mgl-sg** [comment]
I am using ROS melodic, I did managed to solve these issues by running launching the joint_state_publisher node, not sure if there is a better way?

**Comment by grassjelly** [comment]
That's strange because ros_control is supposed to publish the joint_states when in Gazebo. Are you able to walk the robot?

**Comment by mgl-sg** [comment]
Yes I am able to walk the robot using the champ_teleop pkg, the specfic changes I made are as follows 
1. Lauching the joint_state_publisher node within decription.launch
2. Include the joint_state_publisher gazebo plugin for gazebo in champ.urdf
3. Lastly the key thing was setting the controller spawner in gazebo.launch to continuously respawn. As I kept getting the following warning 
[WARN]: Controller Spawner couldn't find the expected controller_manager ROS Interface

**Comment by grassjelly** [comment]
I see. Do you have ros_control and gazebo_ros_control installed? Btw @mgl-sg , do you happen to be from Singapore?

**Comment by mgl-sg** [comment]
Yes I have both installed, had a friend try to run the same simulation and he had the same issues as well until he made the changes above. Yes I am from Singapore

**Comment by grassjelly** [comment]
cool! Is there any way I can reach out to you? Email?  @mgl-sg
