### ISSUE TITLE
Gazebo spawn error

### ISSUE THREAD

**Issue by offjangir** [chvmp/champ#58]
![Screenshot from 2021-06-16 23-07-44](https://user-images.githubusercontent.com/60678034/122266754-c1499100-cef7-11eb-9568-088bb8f200c9.png)

**Comment by PranshuTople** [comment]
@offjangir check this video to solve the issue - https://youtu.be/C9quuhNuWIM

**Comment by abdu7rahman** [comment]
how have you managed to solve this??
