### ISSUE TITLE
mini_cheetah cannot work in gazebo

### ISSUE THREAD

**Issue by Jonathan-Twz** [chvmp/champ#6]
Hi, I've tried your demo for mini_cheetah, with command `roslaunch mini_cheetah_config bringup.launch` and then `roslaunch mini_cheetah_config gazebo.launch`. But the robot cannot stand up in gazebo, and come up with the information below:  

[FATAL] [1595421094.629746262]: Failed to unload nodelet '/velocity_smoother' from manager 'nodelet_manager'
[WARN] [1595421124.845966, 1.244000]: Controller Spawner couldn't find the expected controller_manager ROS interface.

The mini_cheetah in gazebo is like:
![image](https://user-images.githubusercontent.com/39961567/88177384-9f5b6780-cbdd-11ea-89fa-bf8b9ba431b5.png)

Could you please help me with what's wrong with my command or how could I fix this bug.

**Comment by grassjelly** [comment]
Hi there, this is the same issue as this https://github.com/chvmp/champ/issues/5 . You need to add the physics elements required for Mini Cheetah.  Meanwhile, you can run it in rviz without modifying the barebones URDF.

**Comment by grassjelly** [comment]
A working Gazebo model for the Mini Cheetah is now available. Please check  https://github.com/chvmp/robots  
![mini_cheetah](https://user-images.githubusercontent.com/5070395/92573248-13e68480-f2b8-11ea-81b6-115aa1423da0.gif)
