### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by syhassan** [chvmp/champ#62]
Hello,

I'm using **ROS Noetic with Ubuntu 20.04** and facing an error when executing catkin_make of a missing header file, urdf_loader.h as follows:

![image](https://user-images.githubusercontent.com/47891763/128524134-bcd77046-e9af-494a-97c8-543d48ccac00.png)

I'm a bit of a beginner, so thank you for your help!

Best regards,
Syed

**Comment by robo4869** [comment]
Did you do the installation as instructed? Here is your loss file: https://github.com/chvmp/libchamp

**Comment by robo4869** [comment]
In here: https://github.com/chvmp/champ/blob/master/.travis.yml I see 2 distro kinetic and melodic, how about you add manually noetic?

**Comment by grassjelly** [comment]
Hey @syhassan did you clone the repo recursively  as instructed here? https://github.com/chvmp/champ#11-clone-and-install-all-dependencies

**Comment by syhassan** [comment]
Thank you for your help! It turns out I wasn't cloning it recursively as you stated!
