### ISSUE TITLE
Cannot control using keyboard

### ISSUE THREAD

**Issue by robo4869** [chvmp/champ#63]
Hi,
I followed section 2.1 about "Walking demo in RVIZ", it seems that using the keyboard doesn't work. Can anyone run? Please help me, it doesn't return any error. Everything else is fine.
Thanks.

**Comment by grassjelly** [comment]
Hey @robo4869, you have to press and hold the keys for it to work

**Comment by grassjelly** [comment]
Hey @robo4869 can you please close this if resolved? Thanks

**Comment by robo4869** [comment]
Thanks for you help
