### ISSUE TITLE
/bin/sh: 1: -std=c++11: not found

### ISSUE THREAD

**Issue by elpimous** [chvmp/champ#78]
Hi. Happy new year All !

system : ubuntu 18.04, running Melodic.
`>> My c++ version :  
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

I followed : 
`git clone --recursive https://github.com/chvmp/champ
git clone https://github.com/chvmp/champ_teleop
cd ..
rosdep install --from-paths src --ignore-src -r -y`

then : 
`catkin_make`

Compilation error :
`[ 83%] Building CXX object champ/champ_gazebo/CMakeFiles/contact_sensor.dir/src/contact_sensor.cpp.o
c++: fatal error: no input files
compilation terminated.
/bin/sh: 1: -std=c++11: not found
champ/champ_gazebo/CMakeFiles/contact_sensor.dir/build.make:62: recipe for target 'champ/champ_gazebo/CMakeFiles/contact_sensor.dir/src/contact_sensor.cpp.o' failed
make[2]: *** [champ/champ_gazebo/CMakeFiles/contact_sensor.dir/src/contact_sensor.cpp.o] Error 127
CMakeFiles/Makefile2:1958: recipe for target 'champ/champ_gazebo/CMakeFiles/contact_sensor.dir/all' failed
make[1]: *** [champ/champ_gazebo/CMakeFiles/contact_sensor.dir/all] Error 2
make[1]: *** Attente des tâches non terminées....
In file included from /home/predator/catkin_ws/src/champ/champ/include/champ/quadruped_base/quadruped_leg.h:32:0,
                 from /home/predator/catkin_ws/src/champ/champ/include/champ/quadruped_base/quadruped_base.h:32,
                 from /home/predator/catkin_ws/src/champ/champ/include/champ/utils/urdf_loader.h:35,
                 from /home/predator/catkin_ws/src/champ/champ_base/include/message_relay.h:38,
                 from /home/predator/catkin_ws/src/champ/champ_base/src/message_relay.cpp:28:
/home/predator/catkin_ws/src/champ/champ/include/champ/quadruped_base/quadruped_joint.h:103:13: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
             const float x() const
...`

I tried too, removing in https://github.com/chvmp/champ/blob/master/champ_gazebo/CMakeLists.txt#L5

Any idea ?

**Comment by grassjelly** [comment]
hi, have you resolved the issue?
