### ISSUE TITLE
How to standup process. 

### ISSUE THREAD

**Issue by elpimous** [chvmp/champ#88]
Hi @grassjelly.
Testing champ with my bldc controllers, under a position mode.
My goal is a fully autonomous robot, so I need a robot who sit down and stand up automatically.

I see that your code only propose an already standed up robot. 
Did you work on a stand up procedure?

Any idea of where I should start?

**Comment by grassjelly** [comment]
Hi you can do it programatically by publishing the body pose. You can take a look here: https://github.com/chvmp/champ_teleop/blob/master/champ_teleop.py#L114

**Comment by elpimous** [comment]
Correct. However, when sit down, body on ground, legs contact to ground are a bit larger than normal walk legs contact.
So, left/right end legs must be larger...
Any idea?
I'd love to be able to move each end legs separately...
Thanks Juan

**Comment by grassjelly** [comment]
hey @elpimous please close the issue if my answer solves your issue
