### ISSUE TITLE
Make Gazebo controller respawn option configurable

### ISSUE THREAD

**Issue by sskorol** [chvmp/champ#93]
Currently, Gazebo `controller_spawner` has a [hardcoded](https://github.com/chvmp/champ/blob/master/champ_gazebo/launch/gazebo.launch#L31) `respawn="false"` arg. There are no issues while running it locally. However, if you try launching `gazebo.launch` in a Docker, `controller_spawner` just times out and exists. It blocks any further teleop attempts as joints' data is not managed anymore. The issue can be fixed by switching `respawn="true"`. In this case, after several timeouts, when Gazebo is ready, this node can be successfully spawned. I propose to make this option configurable so that anyone can pass it as an argument.

**Comment by grassjelly** [comment]
could you send a PR?

**Comment by sskorol** [comment]
@grassjelly just sent :)
